working_dir: '/Volumes/HD/biodata/colocalization-tools'
input:
  gwas:
    file: '/Volumes/HD/biodata/colocalization-tools/raw/gwas/cS2G-gwas-catalog/32242144-GCST90000616-EFO_0004631.h.tsv.gz'
    trait: 'GCST90000616'
    sample_size: 417580
    type: 'cc'
    sep: '	' #optional
    col_name_mapping:
      snp: 'hm_rsid'
      chrom: 'hm_chrom'
      position: 'hm_pos'
      beta: 'hm_beta'
      effect_allele: 'hm_effect_allele'
      other_allele: 'hm_other_allele'
      pvalue: 'p_value'
      se: 'standard_error'
  eqtl:
    file: '/Volumes/HD/biodata/colocalization-tools/raw/eqtl/Whole_Blood.tsv.gz'
    tissue: 'Whole_Blood'
    sample_size: 670
    type: 'quant'
    col_name_mapping:
      snp: 'rsid'
      chrom: 'chromosome'
      position: 'position'
      beta: 'beta'
      alt: 'alt'
      ref: 'ref'
      pvalue: 'pvalue'
      se: 'se'
      gene_id: 'molecular_trait_id'
      maf: 'maf'
  vcf: '/Volumes/HD/biodata/colocalization-tools/raw/vcf/phased_hg38'
  genecode: '/Volumes/HD/biodata/colocalization-tools/raw/genecode/gencode.v26.basic.annotation.gtf.gz'
  ld_block_loci_file: '/Volumes/HD/biodata/colocalization-tools/raw/loci/eur_hg38_ld_block.bed'
  eqtl_finemapping_file: '/Volumes/HD/biodata/colocalization-tools/raw/eqtl/finemapping/v8/v8.vcf.gz'
  prediction_dir: '/Volumes/HD/biodata/colocalization-tools/raw/prediction_model_covariance/mashr'
  twas_model_dir: '/Volumes/HD/biodata/colocalization-tools/raw/twas_model'
p-value_threshold:
  gwas: 5.0E-8
  eqtl: 1.0E-6
neighbour_snp_range: 25
population: 'EUR'
