# finemap v.1.1 refer to http://www.christianbenner.com/index_v1.1.html
finemap:
  corr-config: 0.95
  n-causal-max: 5
  n-config-top: 50000
  n-convergence: 1000
  n-iterations: 100000
  prior-k: 0.0
  prior-std: 0.05
  prob-tol: 0.001
# fastenloc refer to https://github.com/xqwen/fastenloc/tree/master/src
fastenloc:
  total_variant:
  s: 1.0
# coloc refer to https://chr1swallace.github.io/coloc/reference/coloc.abf.html
coloc:
  p1: 1.0E-4
  p2: 1.0E-4
  p12: 1.0E-5